<h1>Register</h1>

<div class="row">
    <div class="col-lg-4 col-md-6 col-sm-8">    

        <?php $form->setAttribute('action', $this->url('register'));?>
        <?php echo $this->form()->openTag($form); ?>
        <div class="form-group">
             <?php echo $this->formRow($form->get('username')); ?>
        </div>
        <div class="form-group">
             <?php echo $this->formRow($form->get('password')); ?>
        </div>
        <div class="form-group">
            <?php echo $this->formRow($form->get('submit')); ?>
        </div>
        <?php echo $this->form()->closeTag(); ?>
  
    </div>
</div>